"""Behavioral regressions for engineering; no rockery execution or cloud calls."""
from __future__ import annotations

import json
import math
from pathlib import Path

import cv2
import ezdxf
import numpy as np
import pytest

from emit.ir import DrawingIR, Entity
from engineering.calibration import estimate_scale, parse_dimension, scale_selected_dxf
from engineering.metrics import compare
from engineering.pipeline import build_proposals, run_engineering, write_ir
from engineering.primitives import build, sample_entity
from engineering.prompts import validate_semantics
from engineering.recognize import recognize_features
from engineering.render import render_dxf_to_image
from engineering.trace import ink_mask, skeleton, prune_spurs, trace_paths
from tools.image_io import imwrite


def drawing(tmp_path, name="input.png"):
    # Independently specified raster fixture, not generated by the template code.
    img = np.full((300, 500, 3), 255, np.uint8)
    cv2.rectangle(img, (30, 30), (465, 265), (0, 0, 0), 2)
    for center in [(70, 70), (425, 70), (70, 225), (425, 225)]:
        cv2.circle(img, center, 15, (0, 0, 0), 2)
    cv2.line(img, (190, 125), (310, 125), (0, 0, 0), 2)
    cv2.line(img, (190, 175), (310, 175), (0, 0, 0), 2)
    cv2.ellipse(img, (190, 150), (25, 25), 0, 90, 270, (0, 0, 0), 2)
    cv2.ellipse(img, (310, 150), (25, 25), 0, -90, 90, (0, 0, 0), 2)
    path = tmp_path / name
    imwrite(path, img)
    return path, img


@pytest.mark.parametrize("rotation", [0, 27, 90, 153])
def test_slot_has_closed_tangent_geometry(rotation):
    entities = build("slot", {"center": [120, 120], "length": 110, "diameter": 30, "rotation": rotation})
    assert [e.type for e in entities].count("arc") == 2
    endpoints = []
    for e in entities:
        samples = sample_entity(e)
        endpoints.extend([samples[0], samples[-1]])
    for i, p in enumerate(endpoints):
        assert min(np.linalg.norm(p-q) for j, q in enumerate(endpoints) if j != i) < 1e-8
    for arc in [e for e in entities if e.type == "arc"]:
        assert (arc.end_angle-arc.start_angle) % 360 == pytest.approx(180)
        for p in (sample_entity(arc)[0], sample_entity(arc)[-1]):
            line = min((e for e in entities if e.type == "line"),
                       key=lambda e: min(math.dist(p, e.start), math.dist(p, e.end)))
            assert abs(float((p-arc.center) @ (np.array(line.end)-line.start))) < 1e-7


def test_rectangle_is_closed_and_holes_are_not_invented():
    rect = build("rectangle", {"center": [5, 6], "width": 8, "height": 4})[0]
    assert rect.closed and len(rect.points) == 4
    holes = build("hole_array", {"centers": [[0, 0], [10, 0], [10, 12]], "radius": 2})
    assert len(holes) == 3
    assert [e.center for e in holes] == [(0, 0), (10, 0), (10, 12)]


@pytest.mark.parametrize("params", [
    {"center": [0, 0], "length": 10, "diameter": 20},
    {"center": [0, 0], "length": -1, "diameter": 2},
    {"center": [float('nan'), 0], "length": 10, "diameter": 2},
])
def test_invalid_template_parameters_are_rejected(params):
    with pytest.raises(ValueError):
        build("slot", params)


def test_raster_recognizes_four_holes_and_slot(tmp_path):
    _, img = drawing(tmp_path)
    ink = ink_mask(img)
    features, _ = recognize_features(ink, skeleton(ink))
    circles = [f for f in features if f.kind == "circle"]
    for center in [(70, 70), (425, 70), (70, 225), (425, 225)]:
        match = min(circles, key=lambda f: math.dist(f.params["center"], center))
        assert math.dist(match.params["center"], center) < 1
        assert abs(match.params["radius"]-15) < 1
    slots = [f for f in features if f.kind == "slot"]
    assert slots, [f.kind for f in features]
    assert slots[0].params["length"] == pytest.approx(170, abs=1.5)
    assert slots[0].params["diameter"] == pytest.approx(50, abs=1.5)


def test_partial_arc_is_not_completed_to_circle():
    img = np.full((120, 160), 255, np.uint8)
    cv2.ellipse(img, (80, 60), (30, 30), 0, 0, 180, 0, 2)
    ink = ink_mask(img)
    features, _ = recognize_features(ink, skeleton(ink))
    assert not any(f.kind == "circle" and f.params["radius"] > 20 for f in features)


@pytest.mark.parametrize("rotation,scale", [(17, 1.), (-23, .75), (90, 1.4)])
def test_library_generalizes_to_transformed_drawings(tmp_path, rotation, scale):
    _, source = drawing(tmp_path)
    matrix = cv2.getRotationMatrix2D((250, 150), rotation, scale)
    matrix[:, 2] += (100, 200)
    image = cv2.warpAffine(source, matrix, (750, 700), borderValue=(255, 255, 255))
    ink = ink_mask(image)
    features, _ = recognize_features(ink, skeleton(ink))
    circles = [f for f in features if f.kind == "circle"]
    for center in [(70, 70), (425, 70), (70, 225), (425, 225)]:
        expected = matrix @ np.array([*center, 1])
        assert any(math.dist(f.params['center'], expected) < 1.5 and
                   abs(f.params['radius']-15*scale) < 1.2 for f in circles)
    assert any(f.kind == 'slot' and abs(f.params['length']-170*scale) < 2 for f in features)


def test_pruning_preserves_open_strokes_and_loops():
    mask = np.zeros((40, 50), bool)
    mask[5, 2:12] = True
    mask[20, 4:40] = True
    mask[17:20, 22] = True  # a genuine short spur on a longer stroke
    mask[28, 30:37] = mask[35, 30:37] = True
    mask[28:36, 30] = mask[28:36, 36] = True
    pruned = prune_spurs(mask, 4)
    assert np.array_equal(pruned[5], mask[5])
    assert np.array_equal(pruned[20], mask[20])
    assert np.array_equal(pruned[28:36], mask[28:36])
    assert not pruned[17:20, 22].any()


def test_trace_never_shortcuts_across_junction():
    mask = np.zeros((15, 15), bool)
    mask[7, 2:13] = True
    mask[2:13, 7] = True
    paths, _ = trace_paths(mask)
    assert len(paths) == 4
    assert all(all(x == 7 for x, y in p) or all(y == 7 for x, y in p) for p in paths)


@pytest.mark.parametrize("shape", [(220, 410), (410, 220), (256, 256)])
def test_dxf_renderer_preserves_canvas_and_coordinates(tmp_path, shape):
    h, w = shape
    ir = DrawingIR(width=w, height=h, entities=[
        Entity(type="line", start=(35, 40), end=(140, 40)),
        Entity(type="circle", center=(100, 135), radius=25),
    ])
    path = tmp_path / 'known.dxf'
    write_ir(ir, path)
    image = np.array(render_dxf_to_image(path, width=w, height=h))
    assert image.shape[:2] == shape
    ink = image.mean(axis=2) < 180
    assert ink[38:42, 50:120].any(axis=0).all()
    ys, xs = np.where(ink)
    assert xs.min() >= 33 and xs.max() <= 142
    assert ys.min() >= 38 and ys.max() <= 162
    assert ezdxf.readfile(path).units == 0


def test_metrics_reject_resizing_and_blank_high_ssim():
    image = np.full((100, 100, 3), 255, np.uint8)
    cv2.line(image, (10, 10), (80, 10), (0, 0, 0), 1)
    with pytest.raises(ValueError):
        compare(image[:90], image)
    blank = np.full_like(image, 255)
    score = compare(blank, image)
    assert score['score'] == 0 and not score['valid']
    assert compare(image, image)['f1'] == 1


def test_historical_style_keeps_original_monochrome_without_autoscale(tmp_path):
    doc = ezdxf.new()
    doc.modelspace().add_line((10, 30), (90, 30), dxfattribs={'color': 3})
    path = tmp_path/'historical.dxf'
    doc.saveas(path)
    image = np.array(render_dxf_to_image(path, width=140, height=80, legacy_style=True))
    assert image.shape == (80, 140, 3)
    assert np.array_equal(image[:, :, 0], image[:, :, 1])
    assert (image[49:52, 20:80, 0] < 180).any(axis=0).all()


def test_serialization_preserves_types_short_lines_and_more_than_100():
    from agents.codegen_agent import geometry_json
    entities = [Entity(type='polyline', points=[(0, 0), (10, 0), (10, 10)], closed=True),
                Entity(type='ellipse', center=(50, 50), major=20, minor=10, rotation=30)]
    entities += [Entity(type='line', start=(i, 0), end=(i, 2)) for i in range(120)]
    serialized = json.loads(geometry_json(DrawingIR(width=200, height=200, entities=entities)))
    assert len(serialized) == 122
    assert serialized[0]['closed'] and serialized[1]['rotation'] == 30
    assert len({e['id'] for e in serialized}) == 122


@pytest.mark.parametrize("text", ['M12', '90°', 'R10', 'Ø20', '4×Ø8', '1:2'])
def test_non_linear_labels_cannot_create_a_scale(text):
    ir = DrawingIR(width=200, height=200, entities=[Entity(type='line', start=(0, 0), end=(100, 0))])
    assert estimate_scale([{'text': text, 'center': [50, 2]}], ir)['mm_per_px'] is None


def dimensions():
    ents = []
    for y in (50, 150):
        ents.extend([Entity(type='line', start=(20, y), end=(120, y)),
                     Entity(type='line', start=(20, y-10), end=(20, y+10)),
                     Entity(type='line', start=(120, y-10), end=(120, y+10))])
    ir = DrawingIR(width=200, height=220, entities=ents)
    ocr = [{'text': '10', 'center': [70, y-15], 'box': [62, y-20, 78, y-10], 'score': .99}
           for y in (50, 150)]
    return ir, ocr


def test_dimension_conflicts_abstain_and_consistent_links_scale():
    ir, ocr = dimensions()
    result = estimate_scale(ocr, ir)
    assert result['mm_per_px'] == pytest.approx(.1)
    ocr[1]['text'] = '20'
    assert estimate_scale(ocr, ir)['status'] == 'conflict'
    assert estimate_scale(ocr[:1], ir)['mm_per_px'] is None


def test_disagreeing_ocr_rotations_cannot_overwrite_dimension():
    ir, ocr = dimensions()
    ocr.append({**ocr[0], 'text': '9', 'score': .98})
    result = estimate_scale(ocr, ir)
    assert result['mm_per_px'] is None
    assert result['ambiguous_ocr']


def test_scaling_preserves_selected_geometry_types(tmp_path):
    ir = DrawingIR(width=300, height=200, entities=build('slot', {
        'center': [100, 100], 'length': 120, 'diameter': 30, 'rotation': 22}))
    source, target = tmp_path/'source.dxf', tmp_path/'scaled.dxf'
    write_ir(ir, source)
    scale_selected_dxf(source, target, .2)
    a, b = ezdxf.readfile(source), ezdxf.readfile(target)
    assert [e.dxftype() for e in a.modelspace()] == [e.dxftype() for e in b.modelspace()]
    assert b.units == ezdxf.units.MM
    for original, scaled in zip(a.modelspace().query('ARC'), b.modelspace().query('ARC')):
        assert scaled.dxf.radius == pytest.approx(original.dxf.radius*.2)


def test_semantic_response_cannot_omit_or_invent_entities():
    with pytest.raises(ValueError):
        validate_semantics({'classifications': []}, ['a'])
    with pytest.raises(ValueError):
        validate_semantics({'classifications': [{'id': 'b', 'role': 'hole'}]}, ['a'])
    assert validate_semantics({'classifications': [{'id': 'a', 'role': 'unknown'}]}, ['a'])


def test_codegen_rounds_use_foreground_score_not_ssim(monkeypatch, tmp_path):
    from agents import codegen_agent as agent
    monkeypatch.setattr(agent, '_wh', lambda image: (100, 100))
    monkeypatch.setattr(agent, '_describe', lambda *args: 'measured drawing')
    monkeypatch.setattr(agent, 'chat', lambda *args, **kwargs: 'pass')
    monkeypatch.setattr(agent, 'run_script', lambda code, path: (True, '', path))
    scores = iter([
        {'ssim': .99, 'f1': .70, 'centerline_chamfer_px': 3, 'p95_px': 5},
        {'ssim': .80, 'f1': .93, 'centerline_chamfer_px': .5, 'p95_px': 1},
    ])
    def scored(dxf, image, png):
        return {**next(scores), 'n_entities': 5, 'ink_ratio_pred': .02, 'ink_ratio_gt': .02,
                'dxf': str(dxf), 'png': str(png), 'valid': True}
    monkeypatch.setattr(agent, '_score_dxf', scored)
    result = agent.codegen_proposal('unused.png', grounded=False, rounds=2, out_dir=tmp_path)
    assert result['f1'] == .93 and result['ssim'] == .8


def test_explicit_offline_entry_and_runs_are_isolated(tmp_path, monkeypatch):
    import tools.vlm
    def no_cloud(*args, **kwargs):
        pytest.fail('Explicit offline engineering pipeline called a cloud model')
    monkeypatch.setattr(tools.vlm, 'ask_vision', no_cloud)
    monkeypatch.setattr(tools.vlm, 'ask_image', no_cloud)
    from core.ensemble import run_ensemble
    image, _ = drawing(tmp_path)
    a = run_ensemble(str(image), out_dir=tmp_path/'runs', use_ocr=False, use_ai_review=False)
    b = run_ensemble(str(image), out_dir=tmp_path/'runs', use_ocr=False, use_cache=True, use_ai_review=False)
    assert a['out_dir'] != b['out_dir']
    assert a['best']['f1'] > .97 and a['template_count'] >= 5
    assert a['best']['dxf'] != b['best']['dxf']
    for result in (a, b):
        assert Path(result['best']['dxf']).is_file()
        assert (Path(result['out_dir'])/'overlay.png').is_file()
        assert (Path(result['out_dir'])/'report.json').is_file()
        assert not ezdxf.readfile(result['best']['dxf']).audit().has_errors
        delivery=Path(result['delivery']['directory'])
        assert list(delivery.iterdir())==[Path(result['delivery']['dxf'])]
        assert delivery!=Path(result['out_dir'])


def test_gui_engineering_worker_uses_selected_result(tmp_path, monkeypatch):
    # Exercise the GUI worker without requiring a native Tk display/runtime.
    import gui
    import core.ensemble
    from types import SimpleNamespace
    selected_dir = tmp_path/'unique_run'
    selected_dir.mkdir()
    selected = selected_dir/'best.dxf'
    selected.write_text('selected geometry', encoding='utf8')
    result = {'out_dir': str(tmp_path/'internal'), 'picked': 'LIBRARY', 'selected_templates': 2,
              'delivery': {'directory':str(selected_dir),'dxf':str(selected),'units':'pixels'},
              'best': {'dxf': str(selected), 'png': str(selected_dir/'best.png'), 'f1': .98},
              'proposals': {'LIBRARY': {'f1': .98, 'n_entities': 10}},
              'calibration': {'status': 'needs_review', 'mm_per_px': None}}
    monkeypatch.setattr(core.ensemble, 'run_ensemble', lambda *a, **kw: result)
    monkeypatch.setattr(gui, 'OUT_DIR', tmp_path/'output')
    app = gui.App.__new__(gui.App)
    messages, opened = [], []
    app.root = SimpleNamespace(after=lambda delay, fn, *args: fn(*args))
    app.log = messages.append
    app.open_file = opened.append
    app.run_btn = app.open_btn = SimpleNamespace(configure=lambda *a, **kw: None)
    app.worker('arbitrary_input.jpg', 'cad')
    assert app.out_dir == selected_dir
    assert opened == [str(selected_dir/'best.png')]
    assert selected.read_text(encoding='utf8') == 'selected geometry'
    assert not any('[错误]' in message for message in messages)
